parameters:
    app.admin_menu:
      # - ["名称", "图标", "uri", "上级部门"]
        - ["root", "", "", "god"]
        - ["首页", "fa-solid fa-house", "/admin/index", "root"]
        - ["组织架构", "fa-solid fa-sitemap", "#", "root"]
        - ["公司架构", "fa-solid fa-building", "/admin/org/corporation", "组织架构"]
        - ["部门管理", "fa-solid fa-people-roof", "/admin/org/department", "组织架构"]
        - ["岗位管理", "fa-solid fa-user-tie", "/admin/org/title", "组织架构"]
        - ["职级管理", "fa-solid fa-layer-group", "/admin/org/grade", "组织架构"]
        - ["人员管理", "fa-solid fa-people-group", "#", "组织架构"]
        - ["人员信息", "fa-solid fa-address-card", "/admin/hr/employee", "人员管理"]